version: '3.8'

services:

  mongodb:
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongodb_dev_data:/data/db
      - ./mongo-entrypoint/:/docker-entrypoint-initdb.d/
    ports:
      - 127.0.0.1:27017:27017
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=ddosdb
      - ME_CONFIG_BASICAUTH_PASSWORD=ddosdbddosdb
    ports:
      - 127.0.0.1:8081:8081
    depends_on:
      - mongodb
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq
    ports:
      - 127.0.0.1:5672:5672

volumes:
  mongodb_dev_data:
