version: '3.7'

services:

  mongodb:
    image: mongo
    container_name: ddosdb_mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongodb-data:/data/db
#      - ./mongo-entrypoint/:/docker-entrypoint-initdb.d/
    expose:
      - 27017
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: ddosdb_mongo_express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    env_file:
      - ./temp/environment.prod
    volumes:
      - mongodb-data
    ports:
      - 127.0.0.1:8081:8081
    depends_on:
      - mongodb
    restart: unless-stopped

  db:
    image: postgres:12.0-alpine
    container_name: ddosdb_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ddosdb
      - POSTGRES_PASSWORD=ddosdb
      - POSTGRES_DB=ddosdb
    expose:
      - 5432
    restart: unless-stopped

  ddosdb:
    container_name: ddosdb_ddosdb
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: gunicorn website.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./temp/environment.prod
    volumes:
      - static_volume:/home/ddosdb/ddosdb-static/
      - data_volume:/home/ddosdb/ddosdb-data/
    expose:
     - 8000
    depends_on:
      - db
      - mongodb
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: ddosdb_nginx
    volumes:
      - static_volume:/home/ddosdb/ddosdb-static/
      - data_volume:/home/ddosdb/ddosdb-data/
      - letsencrypt_volume:/etc/letsencrypt/
      - nginx_etc:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - ddosdb
    restart: unless-stopped

volumes:
  mongodb-data:
  postgres_data:
  static_volume:
  data_volume:
  letsencrypt_volume:
  nginx_etc:
